# Generated by Django 4.2 on 2023-04-27 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='projects/')),
                ('project_title', models.CharField(max_length=150)),
                ('link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='services/')),
                ('service_title', models.CharField(max_length=100)),
                ('service_des', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='ProjectAttribute',
        ),
    ]
